development:
  adapter: postgresql
  database: craigslist_jr_dev
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: craigslist_jr_test
  host: localhost
  pool: 5
  timeout: 5000